### PR TITLE
Hubot 2.3 support

### PR DESCRIPTION
**Pull request by alecgorge**
Does all the things necessary to work with the latest version of Hubot.

### CODE REVIEW

**Comment by unixcharles** [comment]
I hope you don't mind I squashed and cleaned your commits [here](https://github.com/unixcharles/hubot-talker/commit/47b2fc671281bf80253c26d55ad6def244c93833). Let me know if I missed something.

**Comment by alecgorge** [comment]
The only thing I think you missed was the version changes in the package.json file to reflect the usage of the new node api.

**Comment by unixcharles** [comment]
You mean the version of node?

**Comment by alecgorge** [comment]
Yes, and the version of the npm module

On Wed, Aug 1, 2012 at 6:14 AM, Charles Barbier <
reply@reply.github.com

**Pull request closed without merging**
